import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import SiteHeader from "./components/nav/site-header";
import Footer from "./components/nav/footer";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body>
          <SiteHeader />
          <main className="flex flex-col items-center justify-between px-6 py-12 sm:px-10 sm:py-24 min-h-[calc(100vh-12rem)]">
            {children}
          </main>
          <Footer />
      </body>
    </html>
  );
}
